jangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notesApp.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

notesApp/urls.py
from django.urls import path

from . import views

urlpatterns = [     #define urls used in the note app accross the site
    path('', views.Index, name='index'),
    path('notes', views.Notes, name='notes'),
    path('note/<int:pk>', views.EditNote, name='editNote'),
    path('note/<int:pk>/delete', views.DeleteNote, name='deleteNote'),
    path('notes/add', views.CreateNote, name='noteCreate'),
    path('register', views.CreateUser, name='register'),
]

notesApp/models.py
import datetime

from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Note(models.Model):   #define note model for database and api access
    colourChoices = (   #choice of colours
        ('blue', 'Blue'),
        ('red', 'Red'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)   #owner primary key to assign notes too
    title = models.CharField(   #title of note
        max_length=50, help_text="Main description of your task")
    description = models.TextField(     #optional description
        blank=True, null=True, help_text="Any additional information")
    colour = models.CharField(blank=True, null=True,    #option colours from colourChoice
                              max_length=50, choices=colourChoices, help_text="Colour code the note")
    group = models.CharField(   #option group
        blank=True, null=True, max_length=50, help_text="Assign the note to a group")
    dateCreated = models.DateTimeField(     #date created set from servers current date
        auto_now_add=True, verbose_name='date created')
    dateDue = models.DateTimeField(     #option date due set by user
        blank=True, null=True, help_text="Set a reminder date", verbose_name='date due')

    class Meta: #custom ordering of notes
        ordering = ["dateCreated"]

    def __str__(self):  #return title of note for clarity
        return self.title

    def clean(self):    #check for valid due date before submitting
        if self.dateDue is not None:
            if self.dateDue < timezone.now():
                raise ValidationError(
                    {"dateDue": "The due date cannot be in the past!"})

notesApp/forms.py
from django import forms
from .models import Note
from django.contrib.auth.models import User

from bootstrap_datepicker_plus import DateTimePickerInput

class NoteForm(forms.ModelForm):    #note form structure for adding and editing notes, inherited from note model
    class Meta:
        model = Note    #where to inherit
        exclude = ['owner']     #dont include option to change user
        widgets = {'dateDue': DateTimePickerInput(options={     #options for the bootstrap date picker
            "showClose": False,
            "showClear": False,
            "showTodayButton": True,
            "format": "MM/DD/YYYY HH:mm",
        })}

    def __init__(self, *args, **kwargs):    #on creation, add form-control class to inputs
        super(NoteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

from django.contrib.auth.forms import UserCreationForm  #get user create form from django
from django.utils.safestring import mark_safe

class SignUpForm(UserCreationForm):     #create custom sign up form from UserCreationForm
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')   #required email addition entry

    class Meta:
        model = User    #model to structure from
        fields = ('username', 'email', 'password1', 'password2', )  #field to include in form

    def __init__(self, *args, **kwargs):    #on create
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():   #for every field, add form-control class
            field.widget.attrs['class'] = 'form-control'
        self.fields['password1'].help_text = mark_safe(self.fields['password1'].help_text)  #change help text to proper html

notesApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.db.models import Q

from .models import Note
from django.contrib.auth.models import User


def Index(request):     #on index visit
    notesCount = Note.objects.all().count() #get count of main info
    usersCount = User.objects.all().count()
    try:
        latestNote = Note.objects.order_by('-pk')[0]
    except:
        latestNote = None
        #get most recent note
    return render(request, 'notesApp/index.html', {'usersCount': usersCount, 'notesCount': notesCount, 'latestNote': latestNote})


from django.contrib.auth.decorators import login_required

@login_required #require user to login
def Notes(request): #on notes page visit
    search = request.GET.get('search', '')  #if user searched for a note, get all notes that contain the search
    sort = request.GET.get('sort', 'dateCreated')   #if user is sorting, return notes in the order of the sort
    noteList = Note.objects.filter(owner=request.user).filter(
        Q(title__contains=search) | 
     Q(description__contains=search) | 
     Q(group__contains=search) | 
     Q(colour__contains=search)
     ).order_by(sort)   #order the notes

    return render(request, 'notesApp/notes.html', {'noteList': noteList})   #return the note info to the user


from .forms import NoteForm #import note from from forms.py

@login_required
def CreateNote(request):    #on new note page
    if request.method == 'POST':    #if they are making a post request
        form = NoteForm(request.POST)
        if form.is_valid(): #check it
            newNote = form.save(commit=False)
            newNote.owner = request.user    #set owner of note to current user
            newNote.save()  #save it
            return redirect('notes')    #redirec to notes page
    else:
        form = NoteForm()   #if not a post request, display the form
    return render(request, 'notesApp/noteForm.html', {'form': form })   #return form to user

@login_required
def EditNote(request, pk):  #on edit page
    note = get_object_or_404(Note, pk=pk)   #get the note otherwise raise a 404
    if note.owner != request.user:  #check if current user is note owner
        raise Http404("You can only edit your own notes.")
    
    if request.method == 'POST':    #if post request
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('notes')
    else:
        form = NoteForm(instance=note)
    return render(request, 'notesApp/noteForm.html', {'form': form })

@login_required
def DeleteNote(request, pk):    #on delete note page
    note = get_object_or_404(Note, pk=pk)   #get note otherwise return 404
    if note.owner != request.user:  #check if current user is owner
        raise Http404("You can only delete your own notes.")
    note.delete()   #delete the note

    return redirect('notes')    #return to notes page

from django.contrib.auth import login, authenticate
from .forms import SignUpForm

def CreateUser(request):    #create user page
    if request.method == "POST":    #if post request
        form = SignUpForm(request.POST) #make post to server
        if form.is_valid(): #check if data is valid
            form.save() #save the new user
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)   #create new user from inputs
            login(request, user)    #login as the user
            return redirect('notes')    #redirect to notes
    else:
        form = SignUpForm() #if not post, show form

    return render(request, 'notesApp/register.html', {'form': form})    #return form to user

from django.shortcuts import render_to_response
from django.template import RequestContext

jangoMain/notesApp/templates/notesApp/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>
</head>
<body>
    <h1 style="color: rgb(53, 141, 182)">Info Page</h1>
    {{ notes }}
    <br>
    <a href="/">back</a>
</body>
</html>

jangoMain/templates/notesApp/info.html
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>
</head>
<body>
    <h1>Info Page</h1>
    {% if notes %}
        {% for note in notes %}
            <span class="{{ note.colour }}">{{ note.title }}</span>
            <br>
            <b>created:</b> {{ note.dateCreated|naturalday }}<br>
            <b>due:</b> {{ note.dateDue|naturaltime }}
            <br>
            {{ note.colour }}
            <br>
            <br>
            <br>
        {% endfor %}
    {% else %}
        no notes
    {% endif %}
    <br>
    <a href="/">back</a>
</body>
</html>

<style>
    h1 {
        color: rgb(53, 141, 182)
    }

    .red {
        color: rgb(238, 93, 93)
    }

    .blue {
        color: rgb(66, 152, 228)
    }

    .green {
        color: rgb(71, 192, 97)
    }

    .yellow {
        color: rgb(236, 214, 87)
    }
</style>

jangoMain/templates/notesApp/newNote.html
{% extends "base.html" %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token%}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

  
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Jango Notes</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script> {% block head %}{% endblock head %}
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'notesApp/css/style.css' %}">
</head>

<body>

  <nav class="d-lg-none sticky-top navbar navbar-expand-md navbar-dark" style="background-color: #2F2F2F">
    <a href="{% url 'index' %}" class="display-1 navbar-brand">Jango
      <span class="font-weight-bold" style="color: #D1BE7D">Notes</span>
    </a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <span class="navbar-text"></span>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'index' %}" class="nav-link">Home</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'notes' %}" class="nav-link">My Notes</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'noteCreate' %}" class="nav-link">Add Note</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
          <div class="dropdown-menu dropdown-menu-right">
            {% if user.is_authenticated %}
            <span class="dropdown-item">Logged in as:
              <b>{{ user.get_username|title }}</b>
            </span>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'password_reset' %}">Forgot Password</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid h-100">
    <div class="row h-100">

      <nav class="navbar sidenav 
      col-xl-2 col-md-3 
      d-none d-lg-block 
      navbar-dark
      float-right text-right" style="padding: 16px 30px;
      background-color: #2F2F2F">
        <h1 style="font-size: 2em; color: #EBEBEB" class="font-weight-light navbar-brand mr-1" href="#">Jango
          <span class="font-weight-bold" style="color: #D1BE7D">Notes</span>
        </h1>
        <hr class="mt-0 mb-3" style="border-top: solid 1px #CECECE">
        <div class="inner-addon left-addon">
          <i class="material-icons" style="color: #8E8E8E;">
            search
          </i>
          <input type="text" placeholder="search" id="searchInput" class="form-control">
        </div>
        <ul class="navbar-nav font-weight-light" style="font-size: 1.5rem">
          {% block sidebar %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notes' %}">My Notes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'noteCreate' %}">Add Note</a>
          </li>
          {% endblock %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu">
              {% if user.is_authenticated %}
              <span class="dropdown-item">Logged in as:
                <b>{{ user.get_username|title }}</b>
              </span>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'login' %}">Login</a>
              <a class="dropdown-item" href="{% url 'register' %}">Register</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'password_reset' %}">Forgot Password</a>
              {% endif %}
            </div>
          </li>
        </ul>


        <div class="footer px-4 pb-3" style="width: 100%; position: absolute; bottom: 0; right: 0">
          <hr style="border-top: solid 1px #CECECE">
          <ul class="navbar-nav font-weight-light" style="font-size: 1.5rem">
            <li class="nav-item">
              <a id="help" style="color: #CECECE" class="nav-link py-1" href="#">Help
                <i class="footer-icons material-icons">
                  help
                </i>
              </a>
            </li>
            <li class="nav-item">
              <a id="info" style="color: #CECECE" class="nav-link py-1" href="#">About
                <i class="footer-icons material-icons">
                  info
                </i>
              </a>
            </li>
          </ul>
        </div>
      </nav>
      
      <div class="col bg-light px-5 py-4" style="overflow-y: scroll">
        {% block content %}{% endblock %}
      </div>

    </div>
  </div>
</body>

</html>

<script>

  function getParameterByName(name) {
    url = window.location.href;
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
      results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
  }

  function updateQueryStringParameter(uri, key, value) {
    var re = new RegExp("([?&])" + key + "=.*?(&|$)", "i");
    var separator = uri.indexOf('?') !== -1 ? "&" : "?";

    if (uri.match(re)) {
      if (value == getParameterByName('sort') && key == 'sort') {
        if (value.startsWith('-')) {
          value = value.replace('-', '')
        } else {
          value = `-${value}`
        }
      }

      return uri.replace(re, '$1' + key + "=" + value + '$2');
    }
    else {
      return uri + separator + key + "=" + value;
    }
  }

  function query(key, value) {
    url = window.location.href
    window.location.href = updateQueryStringParameter(url, key, value)
  }

  $('document').ready(function () {
    $('#searchInput').val(getParameterByName('search'))
  })

  $('#info').click(function () {
    swal('Made with ❤️ by Leon and Justin! ^_^')
  })

  $('#help').click(function () {
    swal('For help, please refer to user documentation.')
  })

  $('#search').click(function () {
    query('search', $('#searchInput').val())
  })

  $("#searchInput").keyup(function (event) {
    if (event.keyCode === 13) {
      query('search', $('#searchInput').val())
    }
  });

  $('#colour').click(function () {
    query('sort', 'colour')
  })

  $('#group').click(function () {
    query('sort', 'group')
  })

  $('#dateDue').click(function () {
    query('sort', 'dateDue')
  })

</script> {% block script %}{% endblock script %}

templates/notesApp/index.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Welcome to Jango Notes.</h1>
  <p class="lead">A Web App made by Leon Salsiccia and Justin Yuen.</p>
  <p class="lead">Jango Notes lets you save any note you need, catagorise them, colour them, then slap a reminder on them and let you know
    just how much time you have left until a due task!
    <br>Jango Notes also lets you clear off any completed tasks or edit any existing ones!
  </p>
  <hr class="my-4">
  <p class="lead text-center text-md-left mb-0">
    <a class="btn btn-primary btn-lg" href="{% url 'notes' %}" role="button">Get Started</a>
  </p>
</div>
<div class="bg-primary lead text-light rounded p-3">Here are some numbers to oogle at!</div>
<br>
<div class="row">
  <div class="col-12 col-lg-4 mb-3">
    <div class="card" style="height: 218px">
      <div class="card-body text-center">
        <h5 class="card-title">Users Stored</h5>
        <p class="card-text">We are currently storing:</p>
        <span style="font-size: 2rem" class="font-weight-bold text-primary">{{ usersCount }}</span>
        <br>
        <span class="lead">Users</span>
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-4 mb-3">
    <div class="card" style="height: 218px">
      <div class="card-body text-center">
        <h5 class="card-title">Notes Stored</h5>
        <p class="card-text">We are currently storing:</p>
        <span style="font-size: 2rem" class="font-weight-bold text-primary">{{ notesCount }}</span>
        <br>
        <span class="lead">Notes</span>
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-4 mb-3">
    <div class="card" style="height: 218px">
      <div class="card-body text-center">
        <h5 class="card-title">Last Note</h5>
        <p class="card-text">Lastest note created:</p>
        <span style="font-size: 2rem" class="font-weight-bold text-primary">{{ latestNote.dateCreated|naturalday }}</span>
      </div>
    </div>
  </div>
</div>

{% endblock %} 

{% block sidebar %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'index' %}">Home</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'notes' %}">My Notes</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'noteCreate' %}">Add Note</a>
</li>
{% endblock %}

templates/notesApp/noteForm.html
{% extends "base.html" %}

{% block head %}
  {{ form.media }}
{% endblock head %}

{% block content %}
  <h1 id="title" class="display-4 mt-3">Add Note</h1>
  {% if form.errors %}
    <p class="text-danger" >Please correct the errors below.</p>
  {% endif %}
  <br>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p class="text-danger">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
  <br>
  <a href="{% url 'notes' %}" class="lead">back</a>

  <script>
    if ($("#id_title").val()) {
      $('#title').html('Edit Note');
      $('#note-nav').html('Edit Note')
    }
  </script>

{% endblock %}

{% block sidebar %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'index' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'notes' %}">My Notes</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" id="note-nav" href="{% url 'noteCreate' %}">Add Note</a>
  </li>
{% endblock %}

templates/notesApp/notes.html
{% extends "base.html" %} {% load humanize %} {% block content %}
<span class="display-4">{{ user.get_username|title }}'s Notes</span>

<hr style="border-top: 1px solid #707070; margin: 5px 0 20px 0">
<div class="sort-icons">
  <i id="colour" class="material-icons" style="font-size: 48px">
    color_lens
  </i>
  <i id="group" class="material-icons" style="font-size: 48px">
    class
  </i>
  <i id="dateDue" class="material-icons" style="font-size: 48px">
    alarm
  </i>
  <a class="text-danger pl-2" style="position: relative; top: -15px; font-size: 1.3rem" href="{% url 'notes' %}">Clear</a>
  <a style="font-size: 1.8rem;
        color: #727272;
        text-decoration: none;
        position: relative;
        top: -10px" class="float-right" href="{% url 'noteCreate' %}">Add
    <span style="color: #5F9CFF; 
        font-size: 2.6rem; 
        margin-bottom: 20px;">+</span>
  </a>
</div>

{% if noteList %}
<div class="row notelist pr-3">
{% for note in noteList %}
<div class="note col-12 col-lg-6 {{ note.colour }}">
  {% if note.description %}
  <div class="note-title pl-3 py-1">
    {{ note.title|truncatechars:33 }}
    <div class="float-right pt-1 pr-2">
      <a href="{% url 'editNote' note.id %}">
        <i class="edit material-icons text-dark">
          create
        </i>
      </a>
      <a href="{% url 'deleteNote' note.id %}">
        <i class="delete material-icons text-dark">
          clear
        </i>
      </a>
    </div>
  </div>
  {% else %}
  <div class="float-right pt-1 pr-2">
      <a href="{% url 'editNote' note.id %}">
        <i class="edit material-icons text-dark">
          create
        </i>
      </a>
      <a href="{% url 'deleteNote' note.id %}">
        <i class="delete material-icons text-dark">
          clear
        </i>
      </a>
    </div>
  {% endif %}
  <div class="note-body" style="width: 100%; overflow-x: auto; overflow-y: auto; height: 110px;">
    {% if note.description %}
      {{ note.description }}
    {% else %}
      <div class="text-center mt-2 display-4">{{ note.title }}</div>
    {% endif %}
  </div>
  <div style="position: absolute; top: 145px; width: 100%;" class="note-footer">
    <hr class="mt-0 mb-1">
    <span class="pl-1">
      <i class="material-icons" style="position: relative; top: 7px">
        class
      </i> {{ note.group }}</span>
    <span class="float-right pr-1"><i class="material-icons" style="position: relative; top: 7px">
        alarm
      </i> {{ note.dateDue|naturaltime }}</span>
  </div>
</div>
{% endfor %}

</div>
{% else %}
<div class="jumbotron">
  <h1 class="display-4">Hmmm.</h1>
  <p class="lead">You dont have any notes...</p>
  <p class="lead">Lets start adding some!</p>
  <hr class="my-4">
  <a href="{% url 'noteCreate' %}" class="btn btn-primary btn-lg">Add</a>
</div>
{% endif %} {% endblock %} {% block sidebar %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'index' %}">Home</a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="{% url 'notes' %}">My Notes</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'noteCreate' %}">Add Note</a>
</li>
{% endblock %}

templates/notesApp/register.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="display-4 mt-3">Sign up</h1>
  <br>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p class="text-danger">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-primary" type="submit">Sign up</button>
  </form>
{% endblock %}